version: "3.7"
services:
  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
    ports:
      - "3000:3000"
    hostname: client
  users:
    build: ./server/users
    volumes:
      - ./server/users:/usr/src/app
    ports:
      - "3001:3001"
    hostname: users
    depends_on:
      - db
  tasks:
    build: ./server/tasks
    volumes:
      - ./server/tasks:/usr/src/app
    ports:
      - "3002:3002"
    hostname: tasks
    depends_on:
      - db
  db:
    image: mongo:latest
    volumes:
      - ./db:/usr/src/db
    ports:
      - "27017:27017"
